project/WebAppProject/WebApplicationProject_sucks/Models/ProfessionalPending.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplicationProject_sucks.Models
{
    public class ProfessionalPending
    {
        [Key]
        [ForeignKey("User")]
        public string UserName {set; get;}
        public User User { get; set; }

        [Required(ErrorMessage = "Profession is required")]
        [ForeignKey("Profession")]
        public string Profession_Name { get; set; }
        public Profession Profession { get; set; }

        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set; }//education related- requires approvement

      
        //categories
        public virtual ICollection<PendingToCategory> ProfessionalCategories { get; set; }

        //application files
        public virtual ICollection<PendingFile> ApplyFiles { get; set; }
    }
}

project/WebAppProject/WebApplicationProject_sucks/Controllers/ProfessionalPendingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationProject_sucks;
using WebApplicationProject_sucks.Models;

namespace WebApplicationProject_sucks.Controllers
{
    public class ProfessionalPendingsController : Controller
    {
        private MyDB db = new MyDB();

        // GET: ProfessionalPendings
        public ActionResult Index()
        {
            var professionalPendings = db.ProfessionalPendings.Include(p => p.Profession).Include(p => p.User);
            return View(professionalPendings.ToList());
        }

        // GET: ProfessionalPendings/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProfessionalPending professionalPending = db.ProfessionalPendings.Find(id);
            if (professionalPending == null)
            {
                return HttpNotFound();
            }
            return View(professionalPending);
        }

        // GET: ProfessionalPendings/Create
        public ActionResult Create()
        {
            ViewBag.Profession_Name = new SelectList(db.Professions, "Profession_Name", "Profession_Name");
            ViewBag.UserName = new SelectList(db.Users, "UserName", "FirstName");
            return View();
        }

        // POST: ProfessionalPendings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserName,Profession_Name,Description")] ProfessionalPending professionalPending,string[] selectedOptions,HttpPostedFileBase[] applyFiles)
        {
            if (ModelState.IsValid &&selectedOptions!=null&&applyFiles!=null)
            {
                for (int i = 0; i < selectedOptions.Length; i++)
                {//MtM relationship
                    //TODO: figure out if we need more adding (to the icollection)
                    db.PendingToCategories.Add(new PendingToCategory(professionalPending.UserName, selectedOptions[i]));
                }

                //formatting our files           
                for (int i = 0; i < applyFiles.Length; i++)
                {//converting each file to a byte array
                    MemoryStream target = new MemoryStream();
                    applyFiles[i].InputStream.CopyTo(target);
                    byte[] content=target.ToArray();
                    //TODO: check if we need more manipulation before saving the byte array                             
                    PendingFile file = new PendingFile(db.PendingFiles.Count(), content, professionalPending.UserName);
                    db.PendingFiles.Add(file);
                }

                //sealing  and adding pending-professional to the DB
                db.ProfessionalPendings.Add(professionalPending);
                db.SaveChanges();

                return RedirectToAction("../HomePage/Home");
            }

          //  ViewBag.Profession_Name = new SelectList(db.Professions, "Profession_Name", "Profession_Name", professionalPending.Profession_Name);
          //ViewBag.UserName = new SelectList(db.Users, "UserName", "FirstName", professionalPending.UserName);
            return View(professionalPending);

        }

        // GET: ProfessionalPendings/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProfessionalPending professionalPending = db.ProfessionalPendings.Find(id);
            if (professionalPending == null)
            {
                return HttpNotFound();
            }
            ViewBag.Profession_Name = new SelectList(db.Professions, "Profession_Name", "Profession_Name", professionalPending.Profession_Name);
            ViewBag.UserName = new SelectList(db.Users, "UserName", "FirstName", professionalPending.UserName);
            return View(professionalPending);
        }

        // POST: ProfessionalPendings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserName,Profession_Name,Description")] ProfessionalPending professionalPending)
        {
            if (ModelState.IsValid)
            {
                db.Entry(professionalPending).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Profession_Name = new SelectList(db.Professions, "Profession_Name", "Profession_Name", professionalPending.Profession_Name);
            ViewBag.UserName = new SelectList(db.Users, "UserName", "FirstName", professionalPending.UserName);
            return View(professionalPending);
        }

        // GET: ProfessionalPendings/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProfessionalPending professionalPending = db.ProfessionalPendings.Find(id);
            if (professionalPending == null)
            {
                return HttpNotFound();
            }
            return View(professionalPending);
        }

        // POST: ProfessionalPendings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ProfessionalPending professionalPending = db.ProfessionalPendings.Find(id);
            db.ProfessionalPendings.Remove(professionalPending);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

project/WebAppProject/WebApplicationProject_sucks/Views/ProfessionalPendings/Create.cshtml
@model WebApplicationProject_sucks.Models.ProfessionalPending

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Content/Professional.css?ver=<?php echo rand(111,999)?" type="text/css">
    <title>Create</title>
</head>
<body>
    <h4>Professional Addition</h4>
    @using (Html.BeginForm("Create", "ProfessionalPendings", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <p id="demo">hey and welcome: @(Session["UserName"])</p>


        @Html.HiddenFor(model => model.UserName, new { Value = Session["UserName"] })

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">

            @{
                MyDB db = new MyDB();

                List<SelectListItem> listOfProfessions = new List<SelectListItem>();
                foreach (var item in db.Professions)
                {
                    listOfProfessions.Add(new SelectListItem { Text = item.Profession_Name, Value = item.Profession_Name });
                }
            }
            @Html.DropDownListFor(model => model.Profession_Name, listOfProfessions, "Select your profession")
        </div>
        <div class="form-group">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", placeholder = "Describe your specialty" } })
        </div>

        <div class="form-group">
            @{

                List<SelectListItem> listOfCategories = new List<SelectListItem>();
                foreach (var item in db.Categories)
                {
                    listOfCategories.Add(new SelectListItem { Text = item.Name, Value = item.Name });
                }
            }
            <label>Select your specialties</label>
            @Html.ListBox("selectedOptions", listOfCategories)
        </div>


        <input type="file" id="applyFiles" name="applyFiles" accept=".pdf" multiple > <br><br>

        <div class="form-group">
            <input type="submit" value="Send for verification" class="btn btn-default" />
        </div>
        @Html.ActionLink("Cancel", "../HomePage/Home")
    </div>
    }

</body>
</html>

project/WebAppProject/WebApplicationProject_sucks/Views/ProfessionalPendings/Delete.cshtml
@model WebApplicationProject_sucks.Models.ProfessionalPending

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProfessionalPending</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Profession.Profession_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Profession.Profession_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

project/WebAppProject/WebApplicationProject_sucks/Views/ProfessionalPendings/Details.cshtml
@model WebApplicationProject_sucks.Models.ProfessionalPending

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ProfessionalPending</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Profession.Profession_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Profession.Profession_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserName }) |
    @Html.ActionLink("Back to List", "Index")
</p>

project/WebAppProject/WebApplicationProject_sucks/Views/ProfessionalPendings/Edit.cshtml
@model WebApplicationProject_sucks.Models.ProfessionalPending

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProfessionalPending</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserName)

        <div class="form-group">
            @Html.LabelFor(model => model.Profession_Name, "Profession_Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Profession_Name", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Profession_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

project/WebAppProject/WebApplicationProject_sucks/Views/ProfessionalPendings/Index.cshtml
@model IEnumerable<WebApplicationProject_sucks.Models.ProfessionalPending>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Profession.Profession_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Profession.Profession_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserName }) |
            @Html.ActionLink("Details", "Details", new { id=item.UserName }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UserName })
        </td>
    </tr>
}

</table>