project/WebAppProject/WebApplicationProject_sucks/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplicationProject_sucks.Controllers
{
    public class SharedController : Controller
    {
        // GET: Shared
        public ActionResult MyProfessionalPages()
        {
            return View();
        }
        public ActionResult FromMy(string FromMy)
        {
            if (FromMy == null)
                return Redirect("/Shared/MyProfessionalPages");
            Session["FromMy"] = FromMy;
            return Redirect("/ProfessionalPages/Create");
        }
    }
}

project/WebAppProject/WebApplicationProject_sucks/Views/Shared/MyProfessionalPages.cshtml
@model IEnumerable<WebApplicationProject_sucks.Models.ProfessionalPage>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <script>
        function mySave() {
            document.getElementById("FromMy").value = "true";
        }
    </script>
    <link rel="stylesheet" href="~/Content/PageIndex.css" type="text/css" />
    <meta name="viewport" content="width=device-width" />
    <title>My Professional Pages</title>
</head>
<body>
    @using (Html.BeginForm("FromMy", "Shared"))
    {
        @Html.AntiForgeryToken()
        <div class="main">
            <p>
                @Html.Hidden("FromMy")
                <input type="submit" value="Create new" onclick="mySave()" class="btn btn-default" /><br />
            </p>
            <table class="table">
                @{ string user = Session["UserName"].ToString();
                    MyDB db = new MyDB();
                <tr>
                    <th>First Name</th>
                    <th>Page Name</th>
                     <th></th>
                </tr>
                    if (db.ProfessionalPages.Where(d => d.UserName == user) != null)
                    {
                        foreach (var item in db.ProfessionalPages.Where(d => d.UserName == user).ToList())
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => db.Users.Find(item.UserName).FirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NameOfPage)
                                </td>
                                <td>

                                    @{ string link = "/ProfessionalPages/Details/" + item.ProfessionalPageID;}
                                    <a href=@link>Details</a>
                                </td>


                            </tr>
                        }
                    }
                }
            </table>
            <a href="../HomePage/Home">Back to home page</a>
            </div>
            }
    </body>
</html>

project/WebAppProject/WebApplicationProject_sucks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">

        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

project/WebAppProject/WebApplicationProject_sucks/Views/Shared/navbar.cshtml
@{
    ViewBag.Title = "navbar";
}
<!DOCTYPE html>

<html>

<head>
    <script>
        //SideBar
        function open_side() {
            document.getElementById("mySidebar").style.display = 'block';
        }
        function close_side() {
            document.getElementById("mySidebar").style.display = "none";
        }
        //searchBar
        function categoryFilter(e) {
           
            document.getElementById("categoryName").value = e.id;
        }
        function contentTypeFilter(e) {
            document.getElementById("contentType").value = e.id;
        }
        function creatorNameFilter(e) {
            document.getElementById("creatorName").value = e.id;
        }
        //dropDown list
        /* When the user clicks on the button,
                            toggle between hiding and showing the dropdown content */
        function dropDown() {
            document.getElementById("myDropdown").style.display = 'block';
        }

    </script>
    <link rel="stylesheet" href="~/Content/navbar.css?ver=<?php echo rand(111,999)?" type="text/css">
</head>
<body>
    @using (Html.BeginForm("FilterdSearch", "HomePage"))
    {
        @Html.AntiForgeryToken()

            if (Session["UserName"] == null)
            {
                <div class="navbar">
                    <a href="" class="active">Home</a>
                    <a href="#">@Html.ActionLink("Log in", "../Users/LogIn")</a>
                    <a href="#">@Html.ActionLink("Register", "../Users/Create")</a>
                </div>
            }

            else
            {
                <div class="navbar">

                    <input type="button" class="sidebar_open" onclick="open_side()" value=☰ />
                    <a href="" class="active">Home</a>
                    <a href="#">@Html.ActionLink("Help points", "../Users/ShowMap")</a>
                    <a href="#">@Html.ActionLink("Log out", "../Users/LogOut")</a>
                    <!-- search bar and drop dwon -->
                    <div class="dropdown" id="dropdown" name="dropdown">
                        <input type="text" autocomplete="off" name="searchBar" id="searchBar" clss="searchBar" placeholder="search for a post" onclick="dropDown()" />
                        <div id="myDropdown" class="dropdown-content">
                            <b>filter by category:</b>
                            <br>
                            <div class="filter-row">
                                @{
                                    var round = 0;
                                    MyDB db = new MyDB();
                                    db.Categories.OrderBy(q => q.Name);
                                    foreach (var q in db.Categories)
                                    {
                                        round++;
                                        if (round == 3)
                                        {
                                            round = 0;
                                            <br>
                                        }
                                        <input type="submit" class="mybtn" id=@q.Name onclick="categoryFilter(this)" value=@q.Name>
                                    }
                                    <input type="submit" class="mybtn" id="all" onclick="categoryFilter(this)" value="cancel">
                                }
                            </div>
                            <br />
                            <b>filter by typeOf content:</b>
                            <br>
                            <div class="row">
                                <div class="filter-row">
                                    <input type="submit" class="mybtn" id="Question-rooms" onclick="contentTypeFilter(this)" value="Question rooms">
                                    <input type="submit" class="mybtn" id="Post" onclick="contentTypeFilter(this)" value="Post">
                                    <input type="submit" class="mybtn" id="all" onclick="contentTypeFilter(this)" value="Cancel">
                                </div>
                            </div>
                            <br />
                            <b>filter by ContentCreators :</b>
                            <br>
                            <div class="filter-row">
                                @{
                                    foreach (var q in db.Users)
                                    {
                                        if (round == 3)
                                        {
                                            round = 0;
                                            <br>
                                        }
                                        <input type="submit" class="mybtn" id=@q.UserName onclick="creatorNameFilter(this)" value=@q.UserName>
                                        round++;
                                    }
                                    <input type="submit" class="mybtn" id="all" onclick="contentTypeFilter(this)" value="Cancel">
                                }
                            </div>
                            @Html.Hidden("categoryName")
                            @Html.Hidden("contentType")
                            @Html.Hidden("creatorName")
                        </div>
                    </div>
                    <!-- end of SearchBar-->
                    <a href="" class="right" style="padding-left:2px">Welcome! @Session["UserName"]</a>
                </div>
               

            }
        }
    

</body>
</html>